stages:
  - lint
  - test
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

default:
  tags:
    - devops-general
  interruptible: true

include:
  - local: .ci/.gitlab-ci-common.yml
  - local: .ci/.gitlab-ci-backend.yml
  - local: .ci/.gitlab-ci-frontend.yml
