package domain

import (
	"encoding/json"
	"os"
	"testing"
)

// The ESCAPING PARITY fixture. The client hand-rolls a JSON encoder so it can measure a body the way
// this package measures it and preserve exact number tokens; a hand-rolled encoder is exactly where a
// private bug lives.
//
// It exists because guessing failed twice in a row. First `JSON.stringify` UNDER-counted, because Go
// HTML-escapes `<`, `>` and `&` into six bytes each. Then the replacement OVER-counted, because Go
// writes short two-byte escapes for backspace and form feed where the client wrote six-byte ones — I
// had the Go source wrong from memory both times, and a client that over-counts refuses what the
// server accepts, which the parity promise forbids as plainly as the other direction (reviewer,
// party [95]).
//
// So the table is not remembered any more. This writes what `encoding/json` ACTUALLY produces, and
// `frontend/src/lib/canaryEncoding.spec.ts` asserts the client reproduces every entry byte for byte.
func TestCanaryEncodingIsPublishedForTheClient(t *testing.T) {
	cases := map[string]string{
		"empty":            "",
		"plain":            "hello",
		"quote":            "he said \"hi\"",
		"backslash":        "a\\b",
		"newline":          "a\nb",
		"carriage":         "a\rb",
		"tab":              "a\tb",
		"backspace":        "a\bb",
		"formfeed":         "a\fb",
		"vertical_tab":     "a\vb",
		"nul":              "a\x00b",
		"bell":             "a\x07b",
		"escape_char":      "a\x1bb",
		"unit_separator":   "a\x1fb",
		"html_lt":          "<",
		"html_gt":          ">",
		"html_amp":         "&",
		"html_mixed":       "<a href='x'>&amp;</a>",
		"line_separator":   "a b",
		"para_separator":   "a b",
		"multibyte_latin":  "héllo",
		"multibyte_cyril":  "мир",
		"multibyte_cjk":    "日本語",
		"emoji":            "a\U0001F642b",
		"all_controls_low": "\x00\x01\x02\x03\x04\x05\x06\x07\b\t\n\v\f\r\x0e\x0f",
		"all_controls_hi":  "\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f",
		"del":              "a\x7fb",
		"mixed_everything": "a\"b\\c\nd<e>f&g h\U0001F642",
	}
	out := map[string]string{}
	for name, in := range cases {
		b, err := json.Marshal(in)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		out[name] = string(b)
	}
	// Marshalled as a MAP too, because that is the shape a body is: keys sorted, and the client's
	// encoder must agree on the whole structure and not only on one string.
	bodyIn := map[string]any{"z": "last", "a": "<first>", "m": true}
	bodyBytes, err := json.Marshal(bodyIn)
	if err != nil {
		t.Fatal(err)
	}

	doc, err := json.MarshalIndent(map[string]any{
		"note": "GENERATED by internal/domain/canaryencoding_test.go. What encoding/json ACTUALLY " +
			"produces. frontend/src/lib/canaryEncoding.spec.ts asserts the client's hand-rolled " +
			"encoder reproduces every entry byte for byte, because the client measures a canary " +
			"body with it and a disagreement in EITHER direction is a client-only rule.",
		"strings":      out,
		"body_input":   bodyIn,
		"body_encoded": string(bodyBytes),
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll("testdata", 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("testdata/canary_encoding.json", append(doc, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
}
