package domain

import (
	"encoding/json"
	"os"
	"testing"
)

// The BOUNDS PARITY gate, and the reason it exists.
//
// Three rounds of independent review found the same shape of defect three times: the typed form
// mirrors most of this validator's rules and silently omits one, so the form promises validity and
// the operator meets a 400. Each round I fixed the named omissions; each round the next one found
// another. Fixing what is named is not a mechanism — it is waiting for the next reviewer.
//
// So the constants stop being something a client remembers. This test writes every bound to a
// fixture, and `frontend/src/lib/canaryBounds.spec.ts` asserts that each is either MIRRORED with the
// same value or listed there as unreachable from the form WITH A REASON. Adding a bound here and
// forgetting the client fails on the client side; changing one here and not there fails too.
func TestCanaryBoundsArePublishedForTheClient(t *testing.T) {
	bounds := map[string]int{
		"CANARY_MAX_BINDINGS":            CanaryMaxBindings,
		"CANARY_MAX_HEADERS_PER_REQUEST": CanaryMaxHeadersPerRequest,
		"CANARY_MAX_HEADER_NAME_BYTES":   CanaryMaxHeaderNameBytes,
		"CANARY_MAX_HEADER_VALUE_BYTES":  CanaryMaxHeaderValueBytes,
		"CANARY_MAX_BODY_DEPTH":          CanaryMaxBodyDepth,
		"CANARY_MAX_BODY_KEYS":           CanaryMaxBodyKeysPerObject,
		"CANARY_MAX_BODY_LIST_ELEMENTS":  CanaryMaxBodyListElements,
		"CANARY_MAX_BODY_BYTES":          CanaryMaxBodyBytes,
		"CANARY_MAX_STRING_LEAF_BYTES":   CanaryMaxStringLeafBytes,
		"CANARY_MAX_MULTIPART_FIELDS":    CanaryMaxMultipartFields,
		"CANARY_MAX_REQUIRED_FIELDS":     CanaryMaxRequiredFields,
		"CANARY_MAX_FAILURE_VALUES":      CanaryMaxFailureValues,
		"CANARY_MIN_SUBMIT_TIMEOUT":      CanaryMinSubmitTimeout,
		"CANARY_MAX_SUBMIT_TIMEOUT":      CanaryMaxSubmitTimeout,
		"CANARY_MIN_POLL_INTERVAL":       CanaryMinPollInterval,
		"CANARY_MAX_POLL_INTERVAL":       CanaryMaxPollInterval,
		"CANARY_MIN_POLL_ATTEMPTS":       CanaryMinPollAttempts,
		"CANARY_MAX_POLL_ATTEMPTS":       CanaryMaxPollAttempts,
		"CANARY_MAX_JSON_PATH_DEPTH":     CanaryMaxJSONPathDepth,
		"CANARY_MAX_JSON_PATH_BYTES":     CanaryMaxJSONPathBytes,
		"CANARY_MAX_CORRELATION_BYTES":   CanaryMaxCorrelationBytes,
	}
	// The count is asserted so that adding a bound to `canary.go` and forgetting THIS map fails here
	// rather than silently reaching no client.
	//
	// What this is NOT, stated because an earlier version of this comment claimed it and the reviewer
	// was right to correct it (party [93]): it is not automatic source-level enumeration. It fires
	// only when a maintainer updates this map, and a constant added to a different block is invisible
	// to it. It narrows the window; it does not close it. Closing it would take parsing the const
	// block — worth doing, and recorded as debt rather than pretended away.
	if len(bounds) != 21 {
		t.Fatalf("the published set has %d bounds; the const block in canary.go has 21 — publish the new one", len(bounds))
	}

	out, err := json.MarshalIndent(map[string]any{
		"note": "GENERATED by internal/domain/canarybounds_test.go. Every bound the typed canary form " +
			"must mirror. frontend/src/lib/canaryBounds.spec.ts asserts each is mirrored with this " +
			"value or declared unreachable from the form with a reason.",
		"bounds": bounds,
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll("testdata", 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("testdata/canary_bounds.json", append(out, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
}
