package domain

import (
	"encoding/json"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The BOUNDS PARITY gate, and the reason it exists.
//
// Three rounds of independent review found the same shape of defect three times: the typed form
// mirrors most of this validator's rules and silently omits one, so the form promises validity and
// the operator meets a 400. Each round I fixed the named omissions; each round the next one found
// another. Fixing what is named is not a mechanism — it is waiting for the next reviewer.
//
// So the constants stop being something a client remembers. This test writes every bound to a
// fixture, and `frontend/src/lib/canaryBounds.spec.ts` asserts that each is either MIRRORED with the
// same value or listed there as unreachable from the form WITH A REASON. Adding a bound here and
// forgetting the client fails on the client side; changing one here and not there fails too.
func TestCanaryBoundsArePublishedForTheClient(t *testing.T) {
	bounds := map[string]int{
		"CANARY_MAX_BINDINGS":            CanaryMaxBindings,
		"CANARY_MAX_HEADERS_PER_REQUEST": CanaryMaxHeadersPerRequest,
		"CANARY_MAX_HEADER_NAME_BYTES":   CanaryMaxHeaderNameBytes,
		"CANARY_MAX_HEADER_VALUE_BYTES":  CanaryMaxHeaderValueBytes,
		"CANARY_MAX_BODY_DEPTH":          CanaryMaxBodyDepth,
		"CANARY_MAX_BODY_KEYS":           CanaryMaxBodyKeysPerObject,
		"CANARY_MAX_BODY_LIST_ELEMENTS":  CanaryMaxBodyListElements,
		"CANARY_MAX_BODY_BYTES":          CanaryMaxBodyBytes,
		"CANARY_MAX_STRING_LEAF_BYTES":   CanaryMaxStringLeafBytes,
		"CANARY_MAX_MULTIPART_FIELDS":    CanaryMaxMultipartFields,
		"CANARY_MAX_REQUIRED_FIELDS":     CanaryMaxRequiredFields,
		"CANARY_MAX_FAILURE_VALUES":      CanaryMaxFailureValues,
		"CANARY_MIN_SUBMIT_TIMEOUT":      CanaryMinSubmitTimeout,
		"CANARY_MAX_SUBMIT_TIMEOUT":      CanaryMaxSubmitTimeout,
		"CANARY_MIN_POLL_INTERVAL":       CanaryMinPollInterval,
		"CANARY_MAX_POLL_INTERVAL":       CanaryMaxPollInterval,
		"CANARY_MIN_POLL_ATTEMPTS":       CanaryMinPollAttempts,
		"CANARY_MAX_POLL_ATTEMPTS":       CanaryMaxPollAttempts,
		"CANARY_MAX_JSON_PATH_DEPTH":     CanaryMaxJSONPathDepth,
		"CANARY_MAX_JSON_PATH_BYTES":     CanaryMaxJSONPathBytes,
		"CANARY_MAX_CORRELATION_BYTES":   CanaryMaxCorrelationBytes,
	}
	// SOURCE-LEVEL enumeration, both directions. The const block in canary.go is parsed and every
	// `CanaryMax*` / `CanaryMin*` identifier it declares must be referenced by the map above; every
	// identifier the map references must exist there. A bound added to the source and not published
	// fails HERE, without anyone remembering a count — which is what the earlier `len(bounds) == 21`
	// could not do (reviewer [93]: it fired only when a maintainer updated the map). Published values
	// are then asserted against the client by canaryBounds.spec.ts.
	declared := canaryBoundIdentifiersDeclaredIn(t, ".")
	published := canaryBoundIdentifiersPublishedBy(t, "canarybounds_test.go")
	for name := range declared {
		if !published[name] {
			t.Errorf("bound %s is declared in the source and NOT published to the client", name)
		}
	}
	for name := range published {
		if !declared[name] {
			t.Errorf("the published map references %s, which no canary source file declares", name)
		}
	}
	if len(published) != len(bounds) {
		t.Fatalf("the map publishes %d values under %d identifiers — one identifier published twice hides a missing bound", len(bounds), len(published))
	}

	out, err := json.MarshalIndent(map[string]any{
		"note": "GENERATED by internal/domain/canarybounds_test.go. Every bound the typed canary form " +
			"must mirror. frontend/src/lib/canaryBounds.spec.ts asserts each is mirrored with this " +
			"value or declared unreachable from the form with a reason.",
		"bounds": bounds,
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll("testdata", 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("testdata/canary_bounds.json", append(out, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
}

// canaryBoundIdentifiersDeclaredIn parses EVERY non-test `canary*.go` in dir and returns every top-level
// constant whose name says it is a bound: CanaryMax… or CanaryMin…. The file set is discovered, not
// listed (reviewer P2 [112]: a hand list is the hand count in another form — a new canary file was
// invisible until somebody remembered to add it). Two rules are the contract, and both are review-
// visible edits rather than silent omissions: a bound lives in a file named `canary*.go`, and it is
// spelled `CanaryMax…`/`CanaryMin…`.
func canaryBoundIdentifiersDeclaredIn(t *testing.T, dir string) map[string]bool {
	t.Helper()
	files, err := filepath.Glob(filepath.Join(dir, "canary*.go"))
	if err != nil {
		t.Fatalf("glob canary sources: %v", err)
	}
	var sources []string
	for _, f := range files {
		if !strings.HasSuffix(f, "_test.go") {
			sources = append(sources, f)
		}
	}
	if len(sources) == 0 {
		t.Fatalf("no canary*.go source in %s — the naming rule or the directory has drifted", dir)
	}
	out := map[string]bool{}
	fset := token.NewFileSet()
	for _, name := range sources {
		f, err := parser.ParseFile(fset, name, nil, 0)
		if err != nil {
			t.Fatalf("parse %s: %v", name, err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, id := range vs.Names {
					if strings.HasPrefix(id.Name, "CanaryMax") || strings.HasPrefix(id.Name, "CanaryMin") {
						out[id.Name] = true
					}
				}
			}
		}
	}
	if len(out) == 0 {
		t.Fatal("no bound constant was found in the canary source — the naming rule or the file list has drifted")
	}
	return out
}

// canaryBoundIdentifiersPublishedBy parses THIS test file and returns the identifiers referenced as
// values inside the `bounds` composite literal of TestCanaryBoundsArePublishedForTheClient.
func canaryBoundIdentifiersPublishedBy(t *testing.T, file string) map[string]bool {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", file, err)
	}
	out := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "TestCanaryBoundsArePublishedForTheClient" {
			return true
		}
		ast.Inspect(fn.Body, func(m ast.Node) bool {
			as, ok := m.(*ast.AssignStmt)
			if !ok || len(as.Lhs) != 1 {
				return true
			}
			if id, ok := as.Lhs[0].(*ast.Ident); !ok || id.Name != "bounds" {
				return true
			}
			lit, ok := as.Rhs[0].(*ast.CompositeLit)
			if !ok {
				return true
			}
			for _, elt := range lit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				if id, ok := kv.Value.(*ast.Ident); ok {
					out[id.Name] = true
				}
			}
			return false
		})
		return false
	})
	if len(out) == 0 {
		t.Fatal("the bounds map was not found in this file — the enumeration reads nothing")
	}
	return out
}

// The enumeration is by DIRECTORY, so a bound declared in a canary file nobody listed is still found.
// Proven against a copy: the real sources plus a `canary_phantom.go` that exists nowhere in the tree.
func TestTheBoundEnumerationSeesAnUnlistedCanaryFile(t *testing.T) {
	dir := t.TempDir()
	real := canaryBoundIdentifiersDeclaredIn(t, ".")
	if len(real) < 21 {
		t.Fatalf("the real directory declares %d bounds, fewer than the 21 known — the glob lost files", len(real))
	}
	srcs, _ := filepath.Glob("canary*.go")
	for _, f := range srcs {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, filepath.Base(f)), b, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	phantom := "package domain\n\nconst CanaryMaxPhantomThing = 7\n"
	if err := os.WriteFile(filepath.Join(dir, "canary_phantom.go"), []byte(phantom), 0o600); err != nil {
		t.Fatal(err)
	}
	got := canaryBoundIdentifiersDeclaredIn(t, dir)
	if !got["CanaryMaxPhantomThing"] {
		t.Fatal("a bound in a canary file the old hand list never named was not found — discovery is not by directory")
	}
	if len(got) != len(real)+1 {
		t.Fatalf("copy declares %d, real %d: the copy should differ by exactly the phantom", len(got), len(real))
	}
}
