package domain

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// FR-030 (D-0234). The bound is counted as CODE POINTS on both sides, so it is asserted at the edge and
// one past it with a Latin and a multibyte sample alike: a 200-rune Cyrillic sentence is 400 bytes and
// must be accepted, or the count is by bytes and the promise is false for half the alphabets.
func validMonitorWithDescription(d string) Monitor {
	return Monitor{ProjectID: "p1", Name: "m", Type: MonitorHTTP, Target: "https://example.com", Description: d,
		IntervalSeconds: 60, TimeoutSeconds: 5, Region: "core"}
}

func TestMonitorDescriptionBoundIsByCodePointOnBothSidesOfTheEdge(t *testing.T) {
	for name, r := range map[string]string{"latin": "a", "cyrillic": "я", "emoji": "🙂"} {
		exact := strings.Repeat(r, MaxMonitorDescriptionRunes)
		if err := validMonitorWithDescription(exact).Validate(); err != nil {
			t.Fatalf("%s: %d code points refused: %v", name, MaxMonitorDescriptionRunes, err)
		}
		over := exact + r
		err := validMonitorWithDescription(over).Validate()
		if err == nil || !strings.Contains(err.Error(), "description") {
			t.Fatalf("%s: %d code points accepted or refused without naming the field: %v", name, MaxMonitorDescriptionRunes+1, err)
		}
	}
}

func TestMonitorDescriptionIsTrimmedAndWhitespaceIsNone(t *testing.T) {
	m := validMonitorWithDescription("   padded   ")
	m.Normalize()
	if m.Description != "padded" {
		t.Fatalf("normalized description = %q", m.Description)
	}
	only := validMonitorWithDescription("  \t \n ")
	only.Normalize()
	if only.Description != "" {
		t.Fatalf("a whitespace-only description survived as %q", only.Description)
	}
	// Trimming happens before counting: 200 runes wrapped in spaces is legal.
	padded := validMonitorWithDescription("  " + strings.Repeat("x", MaxMonitorDescriptionRunes) + "  ")
	if err := padded.Validate(); err != nil {
		t.Fatalf("padding counted against the limit: %v", err)
	}
}

// The bound is published for the form, in the shape the canary bounds already use, so the two counts
// cannot drift silently: frontend/src/lib/monitorBounds.spec.ts reads this fixture.
func TestMonitorBoundsArePublishedForTheClient(t *testing.T) {
	out, err := json.MarshalIndent(map[string]any{
		"note":   "GENERATED by internal/domain/monitordescription_test.go. frontend/src/lib/monitorBounds.spec.ts asserts the form mirrors each value.",
		"bounds": map[string]int{"MAX_MONITOR_DESCRIPTION": MaxMonitorDescriptionRunes},
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("testdata/monitor_bounds.json", append(out, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
}
